name: Check for 00_step.txt and Update README

on:
  workflow_dispatch:  # Allow manual trigger
  push:               # Trigger on push to the repository
    branches:
      - main          # Adjust branch as needed

jobs:
  check-and-update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if 00_step.txt Exists
        id: check_step_file
        run: |
          if [ -f ".github/workflows/steps/00_step.txt" ]; then
            echo "00_step.txt exists."
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "00_step.txt does not exist. Exiting workflow."
            echo "file_exists=false" >> $GITHUB_ENV
            exit 0
          fi

      - name: Run update_readme.sh Script
        if: env.file_exists == 'true'
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/00_step.txt

      - name: Commit Changes to README.md
        if: env.file_exists == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md based on 00_step.txt" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
