name: Check for 00_step.txt and Update README

on:
  workflow_dispatch:  # Allow manual trigger
  push:               # Trigger on push to the repository
    branches:
      - main          # Adjust branch as needed

jobs:
  check-and-update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Source Common Git Operations Script
        run: |
          chmod +x .github/workflows/actions/git_operations.sh
          source .github/workflows/actions/git_operations.sh      

      - name: Check if 00_step.txt Exists
        id: check_step_file
        run: |
          if [ -f ".github/workflows/steps/00_step.txt" ]; then
            echo "00_step.txt exists."
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "00_step.txt does not exist. Exiting workflow."
            echo "file_exists=false" >> $GITHUB_ENV
            exit 0
          fi

      - name: Update README.md and Commit Changes
        if: env.file_exists == 'true'
        run: |
          setup_git
          update_readme .github/workflows/steps/00_step.txt
          commit_and_push_readme