name: Initialize Repository and Set up Git Configuration

on:
  push:
    branches:
      - main  # Trigger this workflow only when a push to the main branch occurs
  pull_request:
    branches:
      - main  # Trigger this workflow for pull requests targeting main

jobs:
  initialize-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration for commit
        run: |
          # Set commit information directly for this step without global gitconfig
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and switch to a new branch
        run: |
          BRANCH=initialize-repository-branch
          git checkout -b $BRANCH

      - name: Modify files (e.g., README.md or others)
        run: |
          # Example modification (customize as needed)
          echo "This is a new repository initialized by GitHub Actions" >> README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Initialize repository with basic setup"

      - name: Push changes to the repository and set upstream
        run: |
          # Push the new branch and set upstream properly
          git push origin $BRANCH:$BRANCH  # Explicitly set the branch to track with the remote

      - name: Restore main branch
        run: |
          git checkout main
