# .github/workflows/01_upload_index.yml
name: Step 1 - Upload index.html

on:
  workflow_run:
    workflows: ["Initialize Repository and Set up Git Configuration"]  # Trigger this workflow when 00_initialize_repository.yml completes
    types:
      - completed
  push:
    paths:
      - "index.html"  # Also trigger this workflow only when index.html is pushed to the repository

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README for Next Step
        run: |
          # Load content from the txt file and append to README.md
          cat ./.github/workflows/steps/01_step.txt >> README.md
          
          # Stage and commit the updated README.md file
          git add README.md
          git commit -m "Update README with Step 1 instructions"
          git push origin main
