name: Step 1 - Upload index.html

on:
  workflow_run:
    workflows: ["Initialize Repository and Set up Git Configuration"]
    types:
      - completed  # This ensures Step 1 runs only after the initial setup is completed
  push:
    paths:
      - "index.html"  # Only trigger when index.html is pushed (first-time or updates to index.html)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if README.md has already been updated
        run: |
          if ! git diff --exit-code README.md; then
            echo "README.md already updated, skipping commit."
            exit 0
          fi

      - name: Run update_readme.sh script with 01_step.txt
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/01_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated README.md and push changes if modified
        run: |
          git add README.md
          git commit -m "Update README after adding index.html" || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
