name: Step 1 - Upload index.html

on:
  push:
    paths:
      - "index.html"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Source Common Git Operations Script and Run
        run: |
          chmod +x .github/workflows/actions/git_operations.sh
          source .github/workflows/actions/git_operations.sh
          setup_git
          update_readme .github/workflows/steps/01_step.txt
          commit_and_push_readme
