name: Step 1 - Upload index.html

on:
  workflow_run:
    workflows: ["Initialize Repository and Set up Git Configuration"]
    types:
      - completed
  push:
    paths:
      - "index.html"  # Trigger this workflow when index.html is pushed to the repository

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration for commit
        run: |
          # Set commit information directly for this step without global gitconfig
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run update_readme.sh script with 01_step.txt
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/01_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push updated index.html
        run: |
          git add index.html
          git commit -m "Update index.html file"
          git push origin main
