# .github/workflows/01_upload_index.yml
name: Step 1 - Upload index.html

on:
  workflow_run:
    workflows: ["Initialize Repository and Set up Git Configuration"]  # Trigger this workflow after 00_initialize_repository.yml completes
    types:
      - completed
  push:
    paths:
      - "index.html"  # Trigger this workflow when index.html is pushed to the repository

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run update_readme.sh script with 01_step.txt
        run: |
          # Run the update_readme.sh script with the path to the step txt file
          bash .github/scripts/actions/update_readme.sh .github/workflows/steps/01_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
