name: Step 2 - Upload reader.py

on:
  push:
    paths:
      - "reader.py"  # Only trigger on reader.py changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run update_readme.sh script with 02_step.txt
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/02_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
