# .github/workflows/01_upload_index.yml
name: Step 1 - Upload index.html

on:
  workflow_run:
    workflows: ["Initialize Repository and Set up Git Configuration"]
    types:
      - completed
  push:
    paths:
      - "index.html"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load Git configuration from file
        run: |
          # Load the Git configuration file
          if [ -f .github/gitconfig.txt ]; then
            while IFS= read -r line; do
              git config --global "$line"
            done < .github/gitconfig.txt
          fi

      - name: Run update_readme.sh script with 01_step.txt
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/01_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
