name: Step 2 - Upload reader.py

on:
  push:
    paths:
      - "reader.py"  # Trigger only if reader.py is uploaded

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Source Common Git Operations Script
        run: |
          chmod +x .github/workflows/actions/git_operations.sh
          source .github/workflows/actions/git_operations.sh

      - name: Update README.md and Commit Changes
        run: |
          setup_git
          update_readme .github/workflows/steps/02_step.txt
          commit_and_push_readme
