name: Step 2 - Upload Python Word Count Script

on:
  push:
    paths:
      - "reader.py"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README for Next Step
        run: |
          # Load content from the txt file and append to README.md
          cat ./github/workflows/steps/02_step.txt >> README.md
          # Stage and commit the updated README.md file
          git add README.md
          git commit -m "Update README with Step 2 instructions"
          git push origin main