name: Step 3 - Update with Dockerfile

on:
  push:
    paths:
      - "Dockerfile"  # Only trigger on Dockerfile changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run update_readme.sh script with 03_step.txt
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/03_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if README.md was updated
        run: |
          # Check if README.md was modified
          git diff --exit-code README.md || echo "README.md has changes"
  
      - name: Commit updated README.md and push changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes in README.md. Skipping commit."
          else
            git add README.md
            git commit -m "Update README after adding Dockerfile"
            git push origin main
          fi
  
