name: Step 3 - Upload Dockerfile

on:
  push:
    paths:
      - "Dockerfile" # Trigger this workflow when Dockerfile is pushed to the repository

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git for committing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: List files in the repository for debugging
        run: ls -al

      - name: Run update_readme.sh script with 03_step.txt
        run: |
          # Run the update_readme.sh script with the path to the step txt file
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/03_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
