name: Detect File Changes and Update Word Count

on:
  push:
    paths:
      - "file.txt"  # Trigger this workflow when file.txt changes

jobs:
  update-word-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Source Common Git Operations Script
        run: |
          chmod +x .github/workflows/actions/git_operations.sh
          source .github/workflows/actions/git_operations.sh

      - name: Set up Python for word count script
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run the update word count script
        run: |
          chmod +x ./.github/workflows/actions/update_count.sh
          ./.github/workflows/actions/update_count.sh

      - name: Commit any unstaged changes (if any) before pulling from remote
        run: |
          setup_git
          commit_unstaged_changes

      - name: Pull the latest changes from remote main branch before pushing
        run: |
          pull_latest_changes

      - name: Commit changes to index.html if word count was added
        run: |
          commit_and_push_index_html

      - name: Update README.md with new step
        run: |
          setup_git
          update_readme .github/workflows/steps/04_step.txt
          commit_and_push_readme
