name: Deploy

on:
  workflow_run:
    workflows: ["03_upload_dockerfile.yml"]  # This triggers the deploy after Step 3 completes
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker container to update index.html
        run: |
          # Build the Docker image
          docker build -t word-counter .

          # Run the Docker container, mounting the current directory as a volume
          docker run --rm -v $(pwd):/app word-counter

      - name: Copy index.html from Docker container to host
        run: |
          # Copy the updated index.html from the Docker container
          docker cp $(docker ps -q -f "ancestor=word-counter"):/app/index.html ./index.html

      - name: Commit changes to index.html
        run: |
          # Configure git
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # Add, commit, and push the updated index.html
          git add index.html
          git commit -m "Update index.html with word count from Docker"
          git push

      - name: Deploy (optional)
        run: |
          # You can add your deployment logic here if necessary (e.g., deploy to a server)
          echo "Deploying application..."
