name: Detect File Changes and Update Word Count

on:
  push:
    paths:
      - "file.txt"  # Trigger this workflow when file.txt changes

jobs:
  update-word-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python for word count script
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run the update word count script
        run: |
          chmod +x ./.github/workflows/actions/update_count.sh
          ./.github/workflows/actions/update_count.sh

      - name: Check if word count was updated in index.html
        run: |
          cat index.html  # Print the contents of index.html for debugging

      - name: Pull the latest changes from remote main branch before pushing
        run: |
          git pull origin main --rebase

      - name: Commit changes to index.html if word count was added
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Append word count to index.html" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Run update_readme.sh script with 04_step.txt
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/04_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes to README.md if updated
        run: |
          git add README.md
          git commit -m "Update README.md with new step" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
