name: Detect File Changes and Update Word Count

on:
  push:
    paths:
      - "file.txt"  # Trigger this workflow when file.txt changes
  pull_request:
    paths:
      - "trailer.yaml"  # Trigger for pull requests

jobs:
  update-word-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Source Common Git Operations Script and Run All Git Operations
        run: |
          chmod +x .github/workflows/actions/git_operations.sh
          source .github/workflows/actions/git_operations.sh
          setup_git
          commit_unstaged_changes
          pull_latest_changes
          commit_and_push_index_html

      - name: Set up Python for word count script
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run the update word count script
        run: |
          chmod +x ./.github/workflows/actions/update_count.sh
          ./.github/workflows/actions/update_count.sh

      - name: Update README.md and Commit Changes
        run: |
          chmod +x .github/workflows/actions/git_operations.sh
          source .github/workflows/actions/git_operations.sh
          setup_git
          update_readme .github/workflows/steps/04_step.txt
          commit_and_push_readme
