name: Detect File Changes and Update Word Count

on:
  push:
    paths:
      - "file.txt"

jobs:
  update-word-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python for word count script
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run the update word count script
        run: |
          chmod +x ./actions/update_count.sh
          ./actions/update_count.sh
