name: Step 5 - Run Python Test in Docker

on:
  push:
    paths:
      - "readertest.py"  # Trigger when readertest.py is updated
  pull_request:
    paths:
      - "readertest.py"  # Trigger for pull requests

jobs:
  run-unittests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checkout the repository

      - name: Build Docker Image
        run: |
          docker build -t readertest-image .  # Build the Docker image using the Dockerfile

      - name: Run Unit Tests in Docker
        run: |
          docker run --rm readertest-image  # Run the Docker container and execute the unittest

      - name: Source Common Git Operations and Update README.md and Commit Changes
        run: |
          chmod +x .github/workflows/actions/git_operations.sh
          source .github/workflows/actions/git_operations.sh
          setup_git
          update_readme .github/workflows/steps/05_step.txt
          commit_and_push_readme
