name: Run Python Test in Docker

on:
  push:
    paths:
      - "readertest.py"  # Trigger when readertest.py is updated
  pull_request:
    paths:
      - "readertest.py"  # Trigger for pull requests

jobs:
  run-unittests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository
      - name: Set up Git configuration for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build Docker image
        run: |
          docker build -t readertest-image .  # Build the Docker image using the Dockerfile

      - name: Run unit tests in Docker
        run: |
          docker run --rm readertest-image  # Run the Docker container and execute the unittest
      - name: Run update_readme.sh script with 05_step.txt
        run: |
          bash .github/workflows/actions/update_readme.sh .github/workflows/steps/05_step.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Commit changes to README.md if updated
        run: |
          git add README.md
          git commit -m "Update README.md with Step 05 instructions" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
